### ISSUE TITLE
Exercise 4 - aws provider and vpc module version clash

### ISSUE THREAD

**Issue by mohclips** [cloudacademy/terraform-aws#2]
```
terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.55.0, >= 3.63.0"...
- Finding latest version of hashicorp/template...
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/aws:
│ no available releases match the given constraints ~> 3.55.0, >= 3.63.0
```

This is due to the parent main.tf requiring 3.55.0 and the vpc module requiring 3.63.0

A workaround can be done by changing the parent main.tf to match the vpc module version requirements.

Maybe something to mention about versioning in the course next time? :)

**Comment by jeremycook123** [comment]
Thanks for the info re AWS provider versions. I've updated and tested all AWS exercises (1-4) to now work with the latest AWS provider (v3.66.0).
