### ISSUE TITLE
Exercise 4 - API service on port 8080 doesnt work

### ISSUE THREAD

**Issue by lukaevet** [cloudacademy/terraform-aws#7]
Hey, I have tried to launch this exercise number 4 and loadbalancer is pointing that target group on port 8080 is unhealthy and you cant get a response on that port therefore API wont load.

**Comment by jeremycook123** [comment]
Just retried exercise 4 and it worked fine without any issues. Application was fully functional. You do need to allow for a small amount of time after the provisioning completes, for the instances to complete their own bootstrapping process and registration within the target group etc. - maybe this is what you encountered. The web_app_wait_command output contains a bash script to poll the readiness of the deployed app:

"web_app_wait_command" {
  value = "until curl --max-time 5 http://${module.application.dns_name} >/dev/null 2>&1; do echo preparing...; sleep 5; done; echo; echo -e 'Ready!!'"
  description = "Test command - tests readiness of the web app"
}

After provisioning completes - copy and execute the outputted command to check for the app being in a ready state
